name: Push xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Push a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Ping Google
      run: curl https://www.google.com/ping?sitemap=https://PJ568.eu.org/sitemap.xml